name: Publish Python Backend to GitHub Packages

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Dá permissão para o Actions salvar no Packages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # O token nativo, sem configurar nada externo

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ghcr.io/idrispukke/rezende-audio-solutions/rezende-backend:latest
